name: rock64
base: core18
version: '0.1'
summary: Pine64 Rock64 Boot Support
description: |
 Pine64 Rock64 RK3328 U-Boot Snapcraft Gadget
type: gadget
architectures:
  - build-on: amd64
    run-on: arm64

confinement: strict
grade: stable

parts:
  uboot-rock64:
    plugin: nil
    source: https://github.com/mrfixit2001/rockchip-uboot.git
    source-branch: master
    override-build: |
      git apply -v ../../../u-boot-env.patch
      TCHAINVER="$(wget -q -O - \
                 https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/| \
                 html2text -width 200|grep 'x86_64_aarch64-linux-gnu.tar.xz '|cut -d' ' -f2)"
      wget https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/$TCHAINVER
      tar xf $TCHAINVER
      mv $(echo $TCHAINVER|sed 's/.tar.xz$//') toolchain
      # build u-boot
      CROSS_COMPILE=$(pwd)/toolchain/bin/aarch64-linux-gnu- make evb-rk3328_defconfig
      CROSS_COMPILE=$(pwd)/toolchain/bin/aarch64-linux-gnu- make

      mkdir -p $SNAPCRAFT_PART_INSTALL/boot-assets

      # grab the required binary blobs and tools from rockship
      git clone --depth=1 https://github.com/ayufan-rock64/rkbin.git
      tools/mkimage -n rk3328 -T rksd -d rkbin/rk33/rk3328_ddr_786MHz_v1.13.bin $SNAPCRAFT_PART_INSTALL/boot-assets/idbloader.img
      cat rkbin/rk33/rk3328_miniloader_v2.46.bin >> $SNAPCRAFT_PART_INSTALL/boot-assets/idbloader.img
      rkbin/tools/loaderimage --pack --uboot ./u-boot-dtb.bin $SNAPCRAFT_PART_INSTALL/boot-assets/uboot.img 0x200000
      rkbin/tools/trust_merger ../../../RK3328TRUST.ini
      mv trust.img $SNAPCRAFT_PART_INSTALL/boot-assets/

      # put environment in place
      tools/mkenvimage -r -s 131072 -o $SNAPCRAFT_PART_INSTALL/uboot.env ../../../uboot.env.in
      ln -s uboot.env $SNAPCRAFT_PART_INSTALL/uboot.conf
    build-packages:
      - bc
      - bison
      - build-essential
      - device-tree-compiler
      - flex
      - git
      - libpython2.7-dev
      - python-minimal
      - gcc-aarch64-linux-gnu
      - html2text
      - wget
      - swig
